version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: sales_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  mongodb:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb123
      MONGO_INITDB_DATABASE: inventory_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data: